### ISSUE TITLE
opt_in_source

### ISSUE THREAD

**Issue by texasbaptists** [madebyraygun/constant-contact#6]
Thanks for this plugin. One issue I'm facing when testing my site is that if I unsubscribe by an email and want to subscribe again, it doesn't work. In emailing with Constant Contact developers, it seems this would only work part of the API call is `action_by_visitor` instead of `action_by_owner`. I'm wondering if that is something that could be set in form snippet code, or if it would require a change in the `classy-org/constantcontact-php-client` dependency.

**Comment by daltonrooney** [comment]
Thanks for doing the research on this one! It looks like the classy-org client always includes the `action_by_owner` query param in their addContact method. In order to change it, I think we'll need to fork the classy-org client and make that param configurable. 

I need to double-check with the Constant Contact API docs that it's OK to use `action_by_visitor` in this scenario, but I don't see why not since it is indeed a visitor generated action. Can you think of any reason why we would want to make this configurable in the snippet, or could we always use `action_by_visitor` in the form?

**Comment by texasbaptists** [comment]
To me, it makes sense to have code that generates the form for the frontend always be `action_by_visitor`. If way down the road this included integration in the admin area where a manager could add to a list without logging into Constant Contact, then any templates for the manager would be `action_by_owner`.

**Comment by daltonrooney** [comment]
I agree, I read through the docs and `action_by_visitor` makes the most sense for front-end forms. Will try to post an update in the next day or so.

**Comment by daltonrooney** [comment]
So I switched the action_by param to `action_by_visitor` but I get an error "Error: Email address XXX already exists." when I try to resubscribe a user to a list who has been previously removed.

According to the API docs"

> When an existing unsubscribed contact subscribes to a contact list, the PUT call that updates their record must include the query parameter action_by=ACTION_BY_VISITOR. Also, they must be added to a contact list when adding them to the contact collection. The action_by parameter defines who initiated the action of adding the contact.

So it looks like we must do some additional work to support this scenario. First we have to see if the contact already exists. If not, then we can add the contact the usual way (with POST). If yes, then we'll need to get the contact ID and create a new method to PUT the update.

This isn't that complicated, but it's going to take me a little longer than I thought. You can follow updates on this branch: https://github.com/madebyraygun/constant-contact/tree/replace-classy-client Thanks for your patience.

**Comment by texasbaptists** [comment]
Thanks for the update. I'll follow. And don't feel rushed on my account.

**Comment by daltonrooney** [comment]
I've made some additional changes and published them to the `replace-classy-client` branch. Interested in trying this out before I merge it into master and publish to the Plugin Store?

If so, you'll need to uninstall the current version of the plugin via the Craft control panel. Then you can add the dev version with Composer. This is probably best done on a local or testing site, not a live production site.

Open a terminal and cd into your app directory. Run the following Composer commands. 

`composer config minimum-stability dev`
`composer config prefer-stable true`
`composer require madebyraygun/constant-contact:dev-replace-classy-client`

Then log back into the Craft control panel and activate the plugin. Let me know how it goes!

**Comment by texasbaptists** [comment]
We will look into it. Thanks.

**Comment by daltonrooney** [comment]
Merged this feature in and tagged for release. You should see it in your Craft dashboard within a day or so. 👍

**Comment by texasbaptists** [comment]
Sorry I didn't have a chance to review this in a timely manner. Hopefully, I'll get some time in January to revisit this.
